name: Tag Release

on:
  push:
    branches:
      - main

jobs:
  tag-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Octo STS Token
        uses: octo-sts/action@e480437973a6f6ac2e9caa40ecabedc870d76395
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: semantic-release

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.octo-sts.outputs.token }}

      - name: Calculate release version
        id: calculate_new_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          dry_run: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag release
        id: push_tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          custom_tag: ${{ steps.calculate_new_version.outputs.new_version }}
          github_token: ${{ steps.octo-sts.outputs.token }}
